const state={data:[],filtered:[],agenda:[]};
const $=s=>document.querySelector(s);
const fmt=new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'});
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const labels={confirmado:'Confirmado',parcial:'Evidência parcial',em_apuracao:'Em apuração'};
const typeLabels={reuniao:'Reunião',viagem:'Viagem',evento:'Evento',encerramento:'Encerramento'};
const TODAY=(()=>{const t=new Date();return new Date(t.getFullYear(),t.getMonth(),t.getDate())})();
const parseDay=s=>{const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const dayDiff=(a,b)=>Math.round((a-b)/864e5);
const pad2=n=>String(n).padStart(2,'0');

async function init(){try{const res=await fetch('data/mock-data.json');if(!res.ok)throw new Error();state.data=(await res.json()).items;populate();bind();renderLatest();apply()}catch(e){$('#itemsList').innerHTML='<p class="empty">Não foi possível carregar a base. Abra pelo GitHub Pages ou por um servidor local.</p>'}
try{const res=await fetch('data/agenda.json');if(!res.ok)throw new Error();state.agenda=(await res.json()).events.slice().sort((a,b)=>a.start.localeCompare(b.start)||a.end.localeCompare(b.end));bindAgenda();renderAgenda()}catch(e){$('#agendaList').innerHTML='<p class="empty">Não foi possível carregar a agenda. Abra por um servidor local ou pelo GitHub Pages.</p>'}}
function populate(){[...new Set(state.data.map(x=>x.topic))].sort().forEach(x=>$('#topicFilter').add(new Option(x,x)));[...new Set(state.data.map(x=>x.source))].sort().forEach(x=>$('#sourceFilter').add(new Option(x,x)))}
function bind(){['periodFilter','topicFilter','sourceFilter','evidenceFilter'].forEach(id=>$('#'+id).addEventListener('change',apply));$('#searchInput').addEventListener('input',apply);$('#resetFilters').onclick=()=>{['periodFilter','topicFilter','sourceFilter','evidenceFilter'].forEach(id=>$('#'+id).value='all');$('#searchInput').value='';apply()};$('#generateBriefing').onclick=generateBriefing;$('#auditButton').onclick=auditClaim;$('#menuBtn').onclick=()=>{const s=$('#sidebar');s.classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',s.classList.contains('open'))};document.querySelectorAll('.nav-link').forEach(a=>a.onclick=()=>$('#sidebar').classList.remove('open'))}
function apply(){const days=$('#periodFilter').value,topic=$('#topicFilter').value,source=$('#sourceFilter').value,evidence=$('#evidenceFilter').value,q=$('#searchInput').value.trim().toLocaleLowerCase('pt-BR');const max=new Date(Math.max(...state.data.map(x=>new Date(x.date+'T12:00:00'))));const cutoff=new Date(max);if(days!=='all')cutoff.setDate(max.getDate()-Number(days)+1);state.filtered=state.data.filter(x=>(days==='all'||new Date(x.date+'T12:00:00')>=cutoff)&&(topic==='all'||x.topic===topic)&&(source==='all'||x.source===source)&&(evidence==='all'||x.verificationStatus===evidence)&&(!q||[x.title,x.summary,x.topic,x.source,x.region,...x.facts,...x.questions].join(' ').toLocaleLowerCase('pt-BR').includes(q)));render();$('#briefingCard').innerHTML='<div class="briefing-placeholder"><span>✦</span><h3>Recorte atualizado</h3><p>Gere um novo briefing para refletir a busca e os filtros.</p></div>'}
function countBy(arr,key){return arr.reduce((a,x)=>(a[x[key]]=(a[x[key]]||0)+1,a),{})}function sorted(o){return Object.entries(o).sort((a,b)=>b[1]-a[1])}
function render(){const d=state.filtered,topics=countBy(d,'topic'),primary=d.filter(x=>x.sourceType==='Fonte oficial'||x.sourceType==='Base pública').length,alerts=d.filter(x=>x.verificationStatus!=='confirmado').length;$('#recordCount').textContent=d.length;$('#topicCount').textContent=Object.keys(topics).length;$('#alertCount').textContent=alerts;const pct=d.length?Math.round(primary/d.length*100):0;$('#evidencePct').textContent=pct+'%';$('#evidenceRing').style.background=`conic-gradient(var(--mint) 0 ${pct}%,#edf0ec ${pct}% 100%)`;const top=sorted(topics)[0];$('#topTopic').textContent=top?`${top[0]} · ${top[1]} registros`:'Sem dados no recorte';$('#resultCount').textContent=`${d.length} ${d.length===1?'item':'itens'}`;renderTimeline(d);renderTopics(topics,d.length);renderItems(d)}
function renderTimeline(d){const by=d.reduce((a,x)=>{const key=x.date.slice(0,7);a[key]=(a[key]||0)+1;return a},{}),dates=Object.keys(by).sort(),max=Math.max(...Object.values(by),1);$('#timelineChart').innerHTML=dates.length?dates.map(date=>`<div class="bar-wrap"><div class="bar" style="height:${by[date]/max*100}%"></div><b>${by[date]}</b><small>${new Date(date+'-15T12:00:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</small></div>`).join(''):'<p class="empty">Sem dados</p>'}
function renderTopics(topics,total){const max=Math.max(...Object.values(topics),1);$('#topicsChart').innerHTML=sorted(topics).slice(0,6).map(([name,val])=>`<div class="topic-row"><span>${esc(name)}</span><div class="track"><i style="width:${val/max*100}%"></i></div><span>${Math.round(val/total*100)}%</span></div>`).join('')||'<p class="empty">Sem dados</p>'}
function renderItems(d){$('#itemsList').innerHTML=d.map(x=>`<article class="item"><div class="item-source">${esc(x.source)}<small>${fmt.format(new Date(x.date+'T12:00:00')).replace('.','')} · ${esc(x.sourceType)}</small></div><div><div class="item-meta"><span class="evidence ${x.verificationStatus}">${labels[x.verificationStatus]}</span><span>${esc(x.region)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><a href="${esc(x.url)}" target="_blank" rel="noopener">Consultar fonte original ↗</a></div><span class="tag">${esc(x.topic)}</span></article>`).join('')||'<p class="empty">Nenhum item corresponde à busca.</p>'}
function renderLatest(){const latest=[...state.data].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4);$('#latestNews').innerHTML=latest.map((x,i)=>`<a class="latest-item" href="${esc(x.url)}" target="_blank" rel="noopener"><span>${String(i+1).padStart(2,'0')}</span><div><small>${esc(x.topic)} · ${fmt.format(new Date(x.date+'T12:00:00')).replace('.','')}</small><h3>${esc(x.title)}</h3><p>${esc(x.source)}</p></div><b>↗</b></a>`).join('')}
function unique(arr){return [...new Set(arr.filter(Boolean))]}function section(title,items,cls=''){return `<section class="brief-section ${cls}"><h4>${title}</h4><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`}
function generateBriefing(){const d=state.filtered;if(!d.length){$('#briefingCard').innerHTML='<p class="empty">Não há evidência neste recorte. Amplie os filtros.</p>';return}const lead=sorted(countBy(d,'topic'))[0][0],questions=unique(d.flatMap(x=>x.questions)).slice(0,5),criticisms=unique(d.map(x=>x.criticism)).slice(0,4),facts=unique(d.flatMap(x=>x.facts)).slice(0,5),examples=unique(d.map(x=>x.example)).slice(0,3),low=d.filter(x=>x.verificationStatus!=='confirmado').length;$('#briefingCard').innerHTML=`<div class="briefing-header"><span>BRIEFING FACTUAL · ${new Date().toLocaleDateString('pt-BR')}</span><h3>Foco: ${esc(lead)}</h3><p>Baseado em ${d.length} registros públicos. Abra as fontes antes de usar números.</p></div>${section('PERGUNTAS DIFÍCEIS E DÚVIDAS',questions)}${section('CRÍTICAS E RISCOS PÚBLICOS',criticisms)}${section('FATOS DISPONÍVEIS',facts)}${section('EXEMPLOS PARA EXPLICAR',examples)}${section('ALERTAS DE EVIDÊNCIA',[`${low} registros deste recorte são parciais ou estão em apuração.`, 'O briefing organiza informações; não mede opinião pública nem recomenda persuasão individual.'],'alert')}`;$('#briefingCard').scrollTop=0}
function auditClaim(){const text=$('#claimInput').value.trim();if(!text){$('#auditResult').innerHTML='<span>!</span><h3>Insira uma afirmação</h3><p>Cole uma frase ou proposta para iniciar a triagem.</p>';return}const absolute=/\b(maior|melhor|único|todos|ninguém|sempre|nunca|zeramos|acabamos)\b/i.test(text),number=/\d/.test(text),future=/\b(vamos|será|garantiremos|faremos|criaremos)\b/i.test(text),issues=[];if(absolute)issues.push('Há linguagem absoluta. Exija comparação documentada ou substitua por uma formulação verificável.');if(number)issues.push('A frase contém número. Informe período, território, metodologia e link da fonte.');if(future)issues.push('Há promessa ou projeção. Diferencie compromisso, meta, prazo e fonte de financiamento.');if(!issues.length)issues.push('Nenhum risco linguístico óbvio foi detectado, mas a afirmação ainda precisa de fonte e revisão humana.');$('#auditResult').innerHTML=`<span>${issues.length>1?'!':'✓'}</span><h3>${issues.length>1?'Revisão necessária':'Triagem concluída'}</h3><ul>${issues.map(i=>`<li>${esc(i)}</li>`).join('')}</ul><p><b>Próximo passo:</b> vincule a afirmação a um registro do Observatório antes de publicar.</p>`}
function bindAgenda(){const sel=$('#agendaTypeFilter');[...new Set(state.agenda.map(x=>x.type))].forEach(x=>sel.add(new Option(typeLabels[x]||x,x)));sel.addEventListener('change',renderAgenda);$('#agendaHideDone').addEventListener('change',renderAgenda)}
function eventStatus(x){const s=parseDay(x.start),e=parseDay(x.end);if(dayDiff(e,TODAY)<0)return{key:'realizado',label:'Realizado'};const d=dayDiff(s,TODAY);if(d<=0)return{key:'hoje',label:x.start===x.end?'Hoje':'Em andamento'};if(d===1)return{key:'proximo',label:'Amanhã'};return{key:'proximo',label:`Em ${d} dias`}}
function renderNext(ev){if(!ev){$('#agendaNext').innerHTML='<span>PRÓXIMO COMPROMISSO</span><strong>Planejamento concluído</strong><p>Todos os compromissos registrados já foram realizados.</p>';return}const st=eventStatus(ev),s=parseDay(ev.start),date=s.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'});$('#agendaNext').innerHTML=`<span>PRÓXIMO COMPROMISSO</span><strong>${esc(ev.title)}</strong><p>${date}${ev.time?' · '+esc(ev.time):''} · ${ev.locations.map(esc).join(' · ')}</p><b class="agenda-count">${st.label}</b>`}
function agendaItem(x){const s=parseDay(x.start),e=parseDay(x.end),st=eventStatus(x),multi=x.start!==x.end,wd=s.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','');return `<article class="agenda-item ${st.key}"><div class="agenda-date"><b>${multi?`${pad2(s.getDate())}–${pad2(e.getDate())}`:pad2(s.getDate())}</b><small>${multi?`${dayDiff(e,s)+1} dias`:wd}</small></div><div><div class="agenda-meta"><span class="agenda-type ${x.type}">${typeLabels[x.type]||x.type}</span>${x.time?`<span class="agenda-time">${esc(x.time)}</span>`:''}<span class="agenda-status ${st.key}">${st.label}</span></div><h4>${esc(x.title)}</h4><p>${x.locations.map(esc).join(' · ')}</p></div></article>`}
function renderAgenda(){const all=state.agenda;if(!all.length)return;const type=$('#agendaTypeFilter').value,hideDone=$('#agendaHideDone').checked,upcoming=all.filter(x=>dayDiff(parseDay(x.end),TODAY)>=0);$('#agTotal').textContent=all.length;$('#agDone').textContent=all.length-upcoming.length;$('#agWeek').textContent=upcoming.filter(x=>dayDiff(parseDay(x.start),TODAY)<=7).length;$('#agPlaces').textContent=unique(all.flatMap(x=>x.locations)).length;renderNext(upcoming[0]);const list=all.filter(x=>(type==='all'||x.type===type)&&(!hideDone||dayDiff(parseDay(x.end),TODAY)>=0)),months={};list.forEach(x=>{const k=x.start.slice(0,7);(months[k]=months[k]||[]).push(x)});$('#agendaList').innerHTML=Object.keys(months).sort().map(k=>{const name=new Date(k+'-15T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'});return `<div class="agenda-month"><h3>${name[0].toUpperCase()+name.slice(1)}</h3>${months[k].map(agendaItem).join('')}</div>`}).join('')||'<p class="empty">Nenhum compromisso corresponde ao filtro.</p>'}
init();
