const state={data:[],filtered:[]};const $=s=>document.querySelector(s);const fmt=new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'});const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function init(){try{const res=await fetch('data/mock-data.json');if(!res.ok)throw new Error();state.data=(await res.json()).items;populate();bind();apply()}catch(e){$('#itemsList').innerHTML='<p class="empty">Não foi possível carregar a base local. Abra o site por um servidor local ou pelo GitHub Pages.</p>'}}
function populate(){const topics=[...new Set(state.data.map(x=>x.topic))].sort();const sources=[...new Set(state.data.map(x=>x.source))].sort();topics.forEach(x=>$('#topicFilter').add(new Option(x,x)));sources.forEach(x=>$('#sourceFilter').add(new Option(x,x)))}
function bind(){$('#periodFilter').addEventListener('change',apply);$('#topicFilter').addEventListener('change',apply);$('#sourceFilter').addEventListener('change',apply);$('#resetFilters').onclick=()=>{$('#periodFilter').value='7';$('#topicFilter').value='all';$('#sourceFilter').value='all';apply()};$('#generateBriefing').onclick=generateBriefing;$('#menuBtn').onclick=()=>{const s=$('#sidebar');s.classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',s.classList.contains('open'))};document.querySelectorAll('.nav-link').forEach(a=>a.onclick=()=>$('#sidebar').classList.remove('open'))}
function apply(){const days=Number($('#periodFilter').value),topic=$('#topicFilter').value,source=$('#sourceFilter').value;const max=new Date(Math.max(...state.data.map(x=>new Date(x.date+'T12:00:00'))));const cutoff=new Date(max);cutoff.setDate(max.getDate()-days+1);state.filtered=state.data.filter(x=>new Date(x.date+'T12:00:00')>=cutoff&&(topic==='all'||x.topic===topic)&&(source==='all'||x.source===source));render();$('#briefingCard').innerHTML='<div class="briefing-placeholder"><span>✦</span><h3>Recorte atualizado</h3><p>Gere um novo briefing para refletir os filtros selecionados.</p></div>'}
function render(){const d=state.filtered,total=d.reduce((a,x)=>a+x.mentions,0),topics=countBy(d,'topic','mentions'),sources=countBy(d,'sourceType'),sent=countBy(d,'sentiment','mentions'),neutral=total?Math.round((sent.neutral||0)/total*100):0;$('#mentionCount').textContent=total;$('#topicCount').textContent=Object.keys(topics).length;$('#sourceCount').textContent=Object.keys(sources).length;$('#neutralPct').textContent=neutral+'%';$('#sentimentRing').style.background=`conic-gradient(var(--mint) 0 ${neutral}%,#edf0ec ${neutral}% 100%)`;const top=sorted(topics)[0];$('#topTopic').textContent=top?`${top[0]} lidera com ${top[1]} menções`:'Sem dados no recorte';$('#sourceSummary').textContent=Object.keys(sources).join(' · ')||'Sem fontes';$('#resultCount').textContent=`${d.length} ${d.length===1?'item':'itens'}`;renderMini(d);renderTimeline(d);renderTopics(topics,total);renderItems(d)}
function countBy(arr,key,weight){return arr.reduce((a,x)=>(a[x[key]]=(a[x[key]]||0)+(weight?x[weight]:1),a),{})}function sorted(o){return Object.entries(o).sort((a,b)=>b[1]-a[1])}
function renderMini(d){const by=countBy(d,'date','mentions'),vals=Object.values(by),max=Math.max(...vals,1);$('#miniBars').innerHTML=vals.map(v=>`<i style="height:${Math.max(15,v/max*100)}%"></i>`).join('')}
function renderTimeline(d){const by=countBy(d,'date','mentions'),dates=[...new Set(d.map(x=>x.date))].sort(),max=Math.max(...Object.values(by),1);$('#timelineChart').innerHTML=dates.length?dates.map(date=>`<div class="bar-wrap"><div class="bar" style="height:${by[date]/max*100}%"></div><b>${by[date]}</b><small>${fmt.format(new Date(date+'T12:00:00')).replace('.','')}</small></div>`).join(''):'<p class="empty">Sem dados</p>'}
function renderTopics(topics,total){$('#topicsChart').innerHTML=sorted(topics).slice(0,5).map(([name,val])=>`<div class="topic-row"><span>${esc(name)}</span><div class="track"><i style="width:${val/Math.max(...Object.values(topics))*100}%"></i></div><span>${Math.round(val/total*100)}%</span></div>`).join('')||'<p class="empty">Sem dados</p>'}
function renderItems(d){$('#itemsList').innerHTML=d.map(x=>`<article class="item"><div class="item-source">${esc(x.source)}<small>${fmt.format(new Date(x.date+'T12:00:00')).replace('.','')} · ${esc(x.sourceType)}</small></div><div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p></div><span class="tag">${esc(x.topic)}</span></article>`).join('')||'<p class="empty">Nenhum item corresponde aos filtros.</p>'}
function unique(arr){return [...new Set(arr.filter(Boolean))]}
function section(title,items,cls=''){return `<section class="brief-section ${cls}"><h4>${title}</h4><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`}
function generateBriefing(){const d=state.filtered;if(!d.length){$('#briefingCard').innerHTML='<p class="empty">Não há evidência neste recorte para gerar um briefing. Amplie os filtros.</p>';return}const topics=sorted(countBy(d,'topic','mentions')),lead=topics[0][0],questions=unique(d.flatMap(x=>x.questions)).slice(0,4),criticisms=unique(d.map(x=>x.criticism)).slice(0,4),facts=unique(d.map(x=>x.facts)).slice(0,4),examples=unique(d.map(x=>x.example)).slice(0,3);const low=d.filter(x=>/não|ainda|sem |sujeit/i.test(x.facts)).length;$('#briefingCard').innerHTML=`<div class="briefing-header"><span>BRIEFING FACTUAL · ${new Date().toLocaleDateString('pt-BR')}</span><h3>Foco: ${esc(lead)}</h3><p>Baseado em ${d.length} itens públicos e ${d.reduce((a,x)=>a+x.mentions,0)} menções agregadas.</p></div>${section('PERGUNTAS DIFÍCEIS E DÚVIDAS RECORRENTES',questions)}${section('CRÍTICAS PÚBLICAS OBSERVADAS',criticisms)}${section('FATOS E DADOS DISPONÍVEIS',facts)}${section('EXEMPLOS CONCRETOS PARA EXPLICAR',examples)}${section('ALERTAS DE EVIDÊNCIA',[`${low} de ${d.length} itens contêm ressalvas, ausência de dado oficial ou informação ainda preliminar. Confirme em fonte primária antes de afirmar números.`,`Este briefing resume debate público; não mede opinião da população nem recomenda persuasão.`],'alert')}`;$('#briefingCard').scrollTop=0}
init();
