import {readFile} from 'node:fs/promises';
const html=await readFile('index.html','utf8');
const js=await readFile('app.js','utf8');
const data=JSON.parse(await readFile('data/mock-data.json','utf8'));
const required=['hoje','latestNews','observatorio','buscador','copiloto','auditor','trajetoria','conteudo','periodFilter','topicFilter','sourceFilter'];
for(const id of required) if(!html.includes(`id="${id}"`)) throw new Error(`Elemento ausente: ${id}`);
if(/whatsapp/i.test(html)) throw new Error('WhatsApp deve permanecer fora deste MVP');
if(!Array.isArray(data.items)||data.items.length<10) throw new Error('Base pública insuficiente');
for(const item of data.items) for(const key of ['date','source','topic','summary','facts','url','verificationStatus']) if(!item[key]) throw new Error(`Campo ${key} ausente no item ${item.id}`);
if(!js.includes('auditClaim')||!js.includes('generateBriefing')) throw new Error('Módulos funcionais ausentes');
console.log(`Validação concluída: ${data.items.length} registros, ${required.length} componentes e WhatsApp desativado.`);
